
names = ["address"",""alias"",""amortization"",""amortization_schedule"",""application"",""asset"",""assigned_asian_types"",""assigned_credit_decision_reasons"",""assigned_ethnicity_types"",""assigned_hispanic_origin_types"",""assigned_race_types"",""assigned_user_roles"",""buyer_profile"",""cmt_rate"",""company"",""company_assigned_documents"",""company_assigned_roles"",""condition"",""condition_assigned_docs"",""credit_decision"",""credit_decision_factors"",""credit_decision_reason"",""credit_product"",""credit_response"",""deal"",""deal_assigned_parties"",""deal_assigned_tasks"",""deal_metadata"",""deal_party_progress"",""deal_property_relation"",""dealer_details"",""dealer_schedule"",""declarations"",""demographic"",""dit_response"",""document"",""down_payment"",""employment"",""expense"",""fake_pii_mask_data"",""fees"",""home"",""income"",""insurance_product"",""investor_participation"",""investor_program"",""liability"",""loan"",""lut_address_type"",""lut_amortization_schedule_type"",""lut_amortization_type"",""lut_application_section"",""lut_asset_category"",""lut_asset_type"",""lut_assistance_type"",""lut_citizenship_type"",""lut_company_role"",""lut_company_type"",""lut_condition_type"",""lut_contact_point_role"",""lut_county"",""lut_credit_impact"",""lut_decision_type"",""lut_disposition_status"",""lut_document_type"",""lut_employment_classification"",""lut_employment_standing"",""lut_ethnicity_hispanic_origin_type"",""lut_ethnicity_type"",""lut_expense_category"",""lut_expense_type"",""lut_fee_type"",""lut_funds_category"",""lut_funds_source"",""lut_funds_type"",""lut_gender_type"",""lut_geo_state"",""lut_home_condition"",""lut_home_model"",""lut_income_category"",""lut_income_type"",""lut_land_disposition"",""lut_liability_category"",""lut_liability_type"",""lut_loan_purpose"",""lut_loan_type"",""lut_manufacturer"",""lut_marital_status"",""lut_mortgage_type"",""lut_owned_property_status"",""lut_ownership_interest"",""lut_party_role"",""lut_position_type"",""lut_program_type"",""lut_race_asian_type"",""lut_race_type"",""lut_residency_basis"",""lut_sections"",""lut_site_disposition"",""lut_special_employer_classification"",""lut_submission_result_response"",""lut_task_role"",""lut_task_type"",""lut_tax_rate"",""lut_taxing_unit"",""lut_term_length"",""lut_unit_type"",""lut_usage_type"",""lut_user_role"",""mask_pii_data"",""offers"",""owned_property"",""package"",""party"",""person"",""person_assigned_tasks"",""position"",""price_predictions"",""property"",""residence"",""system_state"",""system_state_log"",""task"",""task_assigned_docs"",""terms_of_loan"",""verification"]

file = open('migration.sql'"," 'w')

for name in names:
    line_1 = f'alter table \"public\".\"{name}\" alter column \"_created_at\" set default now();'
    file.write(line_1 + '\n')

    line_2 = f'alter table \"public\".\"{name}\" alter column \"_created_at\" set not null;'
    file.write(line_2 + '\n')

    file.write("" + '\n')

# alter table "public"."alias" alter column "_created_at" set default now();
# alter table "public"."alias" alter column "_created_at" set not null;


reversed = ["verification","terms_of_loan","task_assigned_docs","task","system_state_log","system_state","residence","property","price_predictions","position","person_assigned_tasks","person","party","package","owned_property","offers","mask_pii_data","lut_user_role","lut_usage_type","lut_unit_type","lut_term_length","lut_taxing_unit","lut_tax_rate","lut_task_type","lut_task_role","lut_submission_result_response","lut_special_employer_classification","lut_site_disposition","lut_sections","lut_residency_basis","lut_race_type","lut_race_asian_type","lut_program_type","lut_position_type","lut_party_role","lut_ownership_interest","lut_owned_property_status","lut_mortgage_type","lut_marital_status","lut_manufacturer","lut_loan_type","lut_loan_purpose","lut_liability_type","lut_liability_category","lut_land_disposition","lut_income_type","lut_income_category","lut_home_model","lut_home_condition","lut_geo_state","lut_gender_type","lut_funds_type","lut_funds_source","lut_funds_category","lut_fee_type","lut_expense_type","lut_expense_category","lut_ethnicity_type","lut_ethnicity_hispanic_origin_type","lut_employment_standing","lut_employment_classification","lut_document_type","lut_disposition_status","lut_decision_type","lut_credit_impact","lut_county","lut_contact_point_role","lut_condition_type","lut_company_type","lut_company_role","lut_citizenship_type","lut_assistance_type","lut_asset_type","lut_asset_category","lut_application_section","lut_amortization_type","lut_amortization_schedule_type","lut_address_type","loan","liability","investor_program","investor_participation","insurance_product","income","home","fees","fake_pii_mask_data","expense","employment","down_payment","document","dit_response","demographic","declarations","dealer_schedule","dealer_details","deal_property_relation","deal_party_progress","deal_metadata","deal_assigned_tasks","deal_assigned_parties","deal","credit_response","credit_product","credit_decision_reason","credit_decision_factors","credit_decision","condition_assigned_docs","condition","company_assigned_roles","company_assigned_documents","company","cmt_rate","buyer_profile","assigned_user_roles","assigned_race_types","assigned_hispanic_origin_types","assigned_ethnicity_types","assigned_credit_decision_reasons","assigned_asian_types","asset","application","amortization_schedule","amortization","alias","address"]